package com.sabinhantu.baseapp.helper

class Constants {
    object FragmentTags {
        const val TAG_FRAGMENT = "fragment_tag"
        const val TAG_POP_FRAGMENT = "pop_fragment"
        const val TAG_FRAGMENT_LOGIN_DONOR = "TAG_FRAGMENT_LOGIN_DONOR"
        const val TAG_FRAGMENT_LOGIN_ASKER = "TAG_FRAGMENT_LOGIN_ASKER"
        const val TAG_FRAGMENT_REGISTER_STEP_1 = "TAG_FRAGMENT_REGISTER_STEP_1"
        const val TAG_FRAGMENT_REGISTER_STEP_2_DONOR = "TAG_FRAGMENT_REGISTER_STEP_2_DONOR"
        const val TAG_FRAGMENT_REGISTER_STEP_2_ASKER = "TAG_FRAGMENT_REGISTER_STEP_2_ASKER"

        const val TAG_FRAGMENT_RAISES_DONOR = "TAG_FRAGMENT_RAISES_DONOR"
        const val TAG_FRAGMENT_DONATE_DONOR = "TAG_FRAGMENT_DONATE_DONOR"
        const val TAG_FRAGMENT_PROFILE_DONOR = "TAG_FRAGMENT_PROFILE_DONOR"

        const val TAG_FRAGMENT_DONATIONS_ASKER = "TAG_FRAGMENT_DONATIONS_ASKER"
        const val TAG_FRAGMENT_ASK_ASKER = "TAG_FRAGMENT_ASK_ASKER"
        const val TAG_FRAGMENT_PROFILE_ASKER = "TAG_FRAGMENT_PROFILE_ASKER"

        const val TAG_FRAGMENT_ABOUT = "TAG_FRAGMENT_ABOUT"
        const val TAG_FRAGMENT_SETTINGS = "TAG_FRAGMENT_SETTINGS"
    }
}